apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbgcalc
  labels:
    app: lbgcalc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lbgcalc
      
  template:
    metadata:
      labels:
        app: lbgcalc
        tier: lbgcalc
    spec:
      containers:
        - name: lbgcalc
          image: dockerid/image:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
            name: lbgcalc          
    
---
apiVersion: v1
kind: Service
metadata:
  name: lbgcalc
  labels:
    app: lbgcalc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: lbgcalc
    tier: lbgcalc
  type: LoadBalancer
